import React, { useState, useMemo } from "react";
import {
  Sparkles,
  ShieldAlert,
  CheckCircle,
  AlertTriangle,
  Send,
  PlusCircle,
  RefreshCw,
  Copy,
  Check,
  Flame,
  Scale,
  Zap,
  ArrowRight,
  ShieldCheck,
  FileCheck2,
  ListOrdered,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface AIDraftingAssistantPanelProps {
  currentDocumentText: string;
  onInsertContent: (content: string) => void;
  onReplaceSelection?: (content: string) => void;
  className?: string;
}

type RightPaneTab = "copilot" | "risk" | "compliance";

interface RiskItem {
  id: string;
  severity: "critical" | "moderate" | "advisory";
  title: string;
  description: string;
  statute: string;
  suggestedFix: string;
}

export const AIDraftingAssistantPanel: React.FC<AIDraftingAssistantPanelProps> = ({
  currentDocumentText,
  onInsertContent,
  onReplaceSelection,
  className = "",
}) => {
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState<RightPaneTab>("copilot");
  const [inputPrompt, setInputPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  // Chat message history
  const [messages, setMessages] = useState<
    Array<{
      role: "user" | "assistant";
      text: string;
      suggestions?: string[];
      insertableClause?: string;
    }>
  >([
    {
      role: "assistant",
      text: "Assalam-o-Alaikum Advocate. I am your Pakistani Legal Drafting Co-pilot. I can analyze grounds, verify Order VII Rule 11 compliance, formulate writ petitions under Art. 199, or insert standard statutory clauses.",
      suggestions: [
        "Strengthen Legal Grounds & Precedents",
        "Add Specific Relief s.54 Injunction Grounds",
        "Verify Order VII Rule 11 CPC Compliance",
        "Format QSO Art. 17 Witness Execution Block",
      ],
    },
  ]);

  const quickActionChips = [
    {
      label: "Jurisdiction Analysis",
      prompt: "Analyze the territorial and pecuniary jurisdiction for this plaint under Section 20 CPC and Court Fees Act 1870.",
    },
    {
      label: "Injunction Triple Test",
      prompt: "Draft Order 39 Rules 1 & 2 grounds satisfying the triple test (prima facie case, balance of convenience, irreparable loss).",
    },
    {
      label: "CrPC s.497(2) Bail",
      prompt: "Draft further inquiry grounds under Section 497(2) CrPC emphasizing lack of overt role and delay in FIR.",
    },
    {
      label: "QSO Art. 17 Execution",
      prompt: "Generate an Article 17 Qanun-e-Shahadat Order attestation block with CNIC and witness lines.",
    },
  ];

  const handleSendMessage = async (textToSend?: string) => {
    const prompt = textToSend || inputPrompt;
    if (!prompt.trim() || isGenerating) return;

    const userMsg = { role: "user" as const, text: prompt };
    setMessages((prev) => [...prev, userMsg]);
    if (!textToSend) setInputPrompt("");
    setIsGenerating(true);

    try {
      const payload = {
        prompt,
        draftText: currentDocumentText,
        jurisdiction: "Pakistan",
        module: "legal-drafting",
        stream: false,
      };

      const res = await fetch("/api/retrieval/clauses/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        if (res.status === 401) {
          throw new Error("Chamber session unauthenticated. Please sign in via the Sign In tab (/preview/auth) to enable live AI drafting.");
        }
        const errText = await res.text();
        throw new Error(`${res.status}: ${errText}`);
      }

      const data = await res.json();
      const generatedClause = data.clause || data.text || data.content || "";
      const explanation = data.explanation || data.summary || "Here is the court-ready legal draft generated by the AI legal model:";

      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          text: explanation,
          insertableClause: generatedClause || undefined,
        },
      ]);
    } catch (err: any) {
      console.error("AI Drafting error:", err);
      const errMsg = err?.message || "Communication disrupted. Please try again.";
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          text: `⚠️ ${errMsg}`,
        },
      ]);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopyClause = (text: string, index: number) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopiedIndex(index);
      setTimeout(() => setCopiedIndex(null), 2000);
    });
  };

  // ─── Real-time 6-Pillar Compliance Scanner ────────────────────────────────
  const compliancePillars = useMemo(() => {
    const text = currentDocumentText.toLowerCase();

    return [
      {
        id: "p1",
        title: "Pillar 1: Court Forum & Bench Header",
        description: "Must state full judicial department & court hierarchy.",
        passed:
          text.includes("in the high court") ||
          text.includes("in the court of") ||
          text.includes("in the supreme court") ||
          text.includes("judicial department") ||
          text.includes("this deed"),
        fixText: `IN THE HIGH COURT OF JUDICATURE AT LAHORE\n(JUDICIAL DEPARTMENT)\n\nWrit Petition No. _________ / 2026\n`,
      },
      {
        id: "p2",
        title: "Pillar 2: Complete Parties & CNIC Block",
        description: "Parentage, CNIC numbers, and physical postal addresses.",
        passed:
          text.includes("cnic") ||
          text.includes("resident of") ||
          text.includes("petitioner") ||
          text.includes("plaintiff") ||
          text.includes("parties hereto"),
        fixText: `1. Tariq Mahmood s/o Muhammad Bashir,\n   CNIC No. 35201-1234567-1,\n   Resident of House No. 12, Gulberg III, Lahore.\n                                                ... PETITIONER\n\nVERSUS\n\n1. Province of Punjab through Chief Secretary...\n`,
      },
      {
        id: "p3",
        title: "Pillar 3: Statutory Law & Section Citations",
        description: "Explicit statutory provision governing the petition/contract.",
        passed:
          text.includes("article 199") ||
          text.includes("section 497") ||
          text.includes("section 498") ||
          text.includes("order xxxix") ||
          text.includes("order vii") ||
          text.includes("act") ||
          text.includes("ordinance"),
        fixText: `WRIT PETITION UNDER ARTICLE 199 OF THE CONSTITUTION OF THE ISLAMIC REPUBLIC OF PAKISTAN, 1973\n`,
      },
      {
        id: "p4",
        title: "Pillar 4: Judicial Recital Formula",
        description: "'Respectfully Sheweth' or 'Whereas' recital structure.",
        passed:
          text.includes("respectfully sheweth") ||
          text.includes("sheweth") ||
          text.includes("whereas") ||
          text.includes("now therefore"),
        fixText: `Respectfully Sheweth:\n\n1. That the Petitioner is a law-abiding citizen of Pakistan...\n`,
      },
      {
        id: "p5",
        title: "Pillar 5: Verification on Solemn Affirmation",
        description: "Formal verification clause on oath with deponent signature.",
        passed:
          text.includes("verification") ||
          text.includes("solemn affirmation") ||
          text.includes("deponent") ||
          text.includes("in witness whereof"),
        fixText: `VERIFICATION:\nVerified on oath at Lahore this 22nd day of August, 2026 that contents of paras 1 to 4 are true to my knowledge.\n\nDEPONENT\n`,
      },
      {
        id: "p6",
        title: "Pillar 6: Attestation & Witness Schedule",
        description: "Marginal witnesses with CNIC numbers under QSO Art. 17.",
        passed:
          text.includes("witness") ||
          text.includes("oath commissioner") ||
          text.includes("advocate") ||
          text.includes("counsel"),
        fixText: `PETITIONER\nThrough:\nAdvocate High Court\n\nWITNESS 1: __________________ CNIC: __________________\nWITNESS 2: __________________ CNIC: __________________\n`,
      },
    ];
  }, [currentDocumentText]);

  const passedPillarsCount = compliancePillars.filter((p) => p.passed).length;
  const complianceScore = Math.round((passedPillarsCount / compliancePillars.length) * 100);

  // ─── Real-time Clause Risk Analysis ───────────────────────────────────────
  const riskItems = useMemo<RiskItem[]>(() => {
    const text = currentDocumentText.toLowerCase();
    const risks: RiskItem[] = [];

    if (!text.includes("cnic") && !text.includes("qanun-e-shahadat") && !text.includes("witness")) {
      risks.push({
        id: "r1",
        severity: "critical",
        title: "Missing QSO Art. 17 Witness Execution Block",
        description: "Financial instruments and commercial agreements require two male or one male and two female attesting witnesses with CNICs to be admissible under Pakistani law.",
        statute: "Article 17, Qanun-e-Shahadat Order, 1984",
        suggestedFix: `IN WITNESS WHEREOF, the parties execute this deed before witnesses:\nWITNESS 1: ________________ (CNIC: ________________)\nWITNESS 2: ________________ (CNIC: ________________)`,
      });
    }

    if (!text.includes("section 153") && !text.includes("tax") && !text.includes("withholding")) {
      risks.push({
        id: "r2",
        severity: "moderate",
        title: "Missing Income Tax s.153 Withholding Tax Clause",
        description: "Commercial payments in Pakistan without statutory withholding clarity risk tax disallowance and penalties under ITO 2001.",
        statute: "Section 153, Income Tax Ordinance, 2001",
        suggestedFix: `All payments under this Agreement shall be subject to statutory deduction of withholding tax under Section 153 of the Income Tax Ordinance, 2001 against valid CPR.`,
      });
    }

    if (!text.includes("arbitration act") && !text.includes("arbitrator") && !text.includes("jurisdiction")) {
      risks.push({
        id: "r3",
        severity: "advisory",
        title: "Unspecified Dispute Resolution Forum",
        description: "Draft does not specify whether disputes proceed to arbitration under Arbitration Act 1940 or Civil Courts.",
        statute: "Arbitration Act, 1940 (Sections 2 & 3)",
        suggestedFix: `Any dispute shall be referred to arbitration under the Arbitration Act, 1940 by a sole arbitrator seated in Lahore, Pakistan.`,
      });
    }

    return risks;
  }, [currentDocumentText]);

  return (
    <div className={`flex flex-col h-full space-y-3 ${className}`}>
      {/* 3-Tab Selector Header */}
      <div className="grid grid-cols-3 gap-1 p-1 rounded-xl bg-white border border-[#E5E4E2]">
        <button
          type="button"
          onClick={() => setActiveTab("copilot")}
          className={`py-1.5 px-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all ${
            activeTab === "copilot"
              ? "bg-[#1A1A1A]/10 text-[#1A1A1A] border border-[#1A1A1A]/30 shadow-sm"
              : "text-[#666666] hover:text-[#2D2D2D]"
          }`}
        >
          <Sparkles className="w-3.5 h-3.5" />
          <span>AI Copilot</span>
        </button>

        <button
          type="button"
          onClick={() => setActiveTab("risk")}
          className={`py-1.5 px-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all ${
            activeTab === "risk"
              ? "bg-rose-500/20 text-rose-300 border border-rose-500/40 shadow-sm"
              : "text-[#666666] hover:text-[#2D2D2D]"
          }`}
        >
          <ShieldAlert className="w-3.5 h-3.5" />
          <span>Risks ({riskItems.length})</span>
        </button>

        <button
          type="button"
          onClick={() => setActiveTab("compliance")}
          className={`py-1.5 px-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all ${
            activeTab === "compliance"
              ? "bg-emerald-500/20 text-[#1A1A1A] border border-emerald-500/40 shadow-sm"
              : "text-[#666666] hover:text-[#2D2D2D]"
          }`}
        >
          <CheckCircle className="w-3.5 h-3.5" />
          <span>6-Pillars ({complianceScore}%)</span>
        </button>
      </div>

      {/* Tab 1: AI Copilot */}
      {activeTab === "copilot" && (
        <div className="flex flex-col flex-1 min-h-0 space-y-3">
          {/* Quick Action Prompt Chips */}
          <div className="flex flex-wrap gap-1">
            {quickActionChips.map((chip) => (
              <button
                key={chip.label}
                type="button"
                onClick={() => handleSendMessage(chip.prompt)}
                className="px-2 py-1 rounded bg-white hover:bg-[#F5F4F2] text-[#4A4A4A] hover:text-[#1A1A1A] border border-[#E5E4E2] text-[10px] font-medium transition-colors flex items-center gap-1"
              >
                <Zap className="w-3 h-3 text-[#1A1A1A]" />
                <span>{chip.label}</span>
              </button>
            ))}
          </div>

          {/* Chat Messages Log */}
          <div className="flex-1 overflow-y-auto space-y-3 pr-1 custom-scrollbar">
            {messages.map((msg, idx) => (
              <div
                key={idx}
                className={`p-3 rounded-xl text-xs ${
                  msg.role === "user"
                    ? "bg-[#1A1A1A]/5 border border-[#1A1A1A]/15 text-[#1A1A1A] ml-4"
                    : "bg-[#F5F4F2] border border-[#E5E4E2] text-[#4A4A4A] mr-2"
                }`}
              >
                <div className="flex items-center gap-1.5 mb-1 text-[10px] font-semibold uppercase tracking-wider text-[#666666]">
                  {msg.role === "user" ? (
                    <span className="text-[#1A1A1A]">You</span>
                  ) : (
                    <span className="text-[#1A1A1A] flex items-center gap-1">
                      <Sparkles className="w-3 h-3" />
                      Alwakeel Legal AI
                    </span>
                  )}
                </div>

                <div className="leading-relaxed whitespace-pre-wrap font-sans">
                  {msg.text}
                </div>

                {/* Suggestions */}
                {msg.suggestions && (
                  <div className="mt-2.5 pt-2 border-t border-[#E5E4E2] flex flex-wrap gap-1">
                    {msg.suggestions.map((s) => (
                      <button
                        key={s}
                        type="button"
                        onClick={() => handleSendMessage(s)}
                        className="text-[10px] px-2 py-0.5 rounded bg-white text-[#1A1A1A]/90 border border-[#E5E4E2] hover:bg-[#F5F4F2] transition-colors"
                      >
                        → {s}
                      </button>
                    ))}
                  </div>
                )}

                {/* Insertable Clause Card */}
                {msg.insertableClause && (
                  <div className="mt-3 p-2.5 rounded-lg bg-white border border-[#E5E4E2] space-y-2">
                    <div className="p-2 rounded bg-white/90 font-serif text-[11px] text-[#2D2D2D] whitespace-pre-wrap leading-relaxed max-h-40 overflow-y-auto">
                      {msg.insertableClause}
                    </div>

                    <div className="flex items-center justify-end gap-2">
                      <button
                        type="button"
                        onClick={() => handleCopyClause(msg.insertableClause!, idx)}
                        className="px-2 py-1 rounded bg-[#F5F4F2] hover:bg-[#EBEBEB] text-[#2D2D2D] text-[10px] font-medium border border-[#E5E4E2] transition-colors inline-flex items-center gap-1"
                      >
                        {copiedIndex === idx ? (
                          <>
                            <Check className="w-3 h-3 text-[#1A1A1A]" />
                            <span className="text-[#1A1A1A]">Copied</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3 h-3 text-[#666666]" />
                            <span>Copy</span>
                          </>
                        )}
                      </button>

                      <button
                        type="button"
                        onClick={() => onInsertContent(msg.insertableClause!)}
                        className="px-2.5 py-1 rounded bg-[#1A1A1A] hover:bg-[#2D2D2D] text-white text-[10px] font-bold shadow-sm inline-flex items-center gap-1"
                      >
                        <PlusCircle className="w-3 h-3" />
                        <span>Insert in Draft</span>
                      </button>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Prompt Input Form */}
          <div className="pt-2 border-t border-[#E5E4E2]">
            <div className="relative">
              <textarea
                value={inputPrompt}
                onChange={(e) => setInputPrompt(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    handleSendMessage();
                  }
                }}
                placeholder="Instruct AI (e.g. 'Draft grounds for criminal revision', 'Add indemnity')..."
                rows={2}
                className="w-full pl-3 pr-10 py-2 rounded-xl bg-white border border-[#E5E4E2] text-xs text-[#2D2D2D] placeholder:text-[#666666] focus:outline-none focus:border-[#1A1A1A]/50 resize-none font-sans"
              />
              <button
                type="button"
                onClick={() => handleSendMessage()}
                disabled={isGenerating || !inputPrompt.trim()}
                className="absolute right-2.5 bottom-3 p-1.5 rounded-lg bg-[#1A1A1A] hover:bg-[#2D2D2D] disabled:opacity-40 text-white transition-all shadow-sm"
              >
                {isGenerating ? (
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                ) : (
                  <Send className="w-3.5 h-3.5" />
                )}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Tab 2: Clause Risk Scanner */}
      {activeTab === "risk" && (
        <div className="flex flex-col flex-1 overflow-y-auto space-y-3 pr-1 custom-scrollbar">
          {/* Risk Summary Badge */}
          <div className="p-3 rounded-xl bg-white/90 border border-[#E5E4E2] flex items-center justify-between">
            <div>
              <div className="text-xs font-bold text-[#1A1A1A]">Draft Risk Assessment</div>
              <div className="text-[10px] text-[#666666]">
                Pakistani statutory & judicial enforceability scan
              </div>
            </div>
            <span
              className={`px-2.5 py-1 rounded-full text-xs font-bold font-mono ${
                riskItems.length === 0
                  ? "bg-emerald-500/20 text-[#1A1A1A] border border-[#E5E4E2]"
                  : "bg-rose-500/20 text-rose-300 border border-rose-500/30"
              }`}
            >
              {riskItems.length === 0 ? "100/100 Safe" : `${riskItems.length} Issues`}
            </span>
          </div>

          {riskItems.length === 0 ? (
            <div className="text-center py-12 text-[#666666] text-xs space-y-2">
              <ShieldCheck className="w-10 h-10 mx-auto text-[#1A1A1A]/60" />
              <p className="text-[#4A4A4A] font-semibold">No critical statutory risks detected.</p>
              <p className="text-[11px] text-[#666666]">
                Your draft complies with primary Pakistani court pleading requirements.
              </p>
            </div>
          ) : (
            riskItems.map((risk) => (
              <div
                key={risk.id}
                className="p-3 rounded-xl bg-[#F5F4F2] border border-[#E5E4E2] space-y-2"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="space-y-1">
                    <span
                      className={`text-[9px] px-1.5 py-0.5 rounded font-mono font-bold uppercase ${
                        risk.severity === "critical"
                          ? "bg-rose-500/20 text-rose-300 border border-rose-500/30"
                          : "bg-[#1A1A1A]/10 text-[#1A1A1A] border border-[#1A1A1A]/20"
                      }`}
                    >
                      {risk.severity} Risk
                    </span>
                    <h4 className="text-xs font-semibold text-[#1A1A1A] leading-snug">
                      {risk.title}
                    </h4>
                  </div>
                </div>

                <p className="text-[11px] text-[#666666] leading-relaxed">
                  {risk.description}
                </p>

                <div className="text-[10px] text-[#1A1A1A]/90 font-serif">
                  Statute: {risk.statute}
                </div>

                <div className="pt-2 border-t border-[#E5E4E2] flex items-center justify-between">
                  <span className="text-[10px] text-[#666666]">AI Redline Available</span>
                  <button
                    type="button"
                    onClick={() => {
                      onInsertContent(risk.suggestedFix);
                      toast({
                        title: "AI Redline Applied",
                        description: `Inserted fix for ${risk.title}.`,
                      });
                    }}
                    className="inline-flex items-center gap-1 px-2.5 py-1 rounded bg-[#1A1A1A] hover:bg-[#2D2D2D] text-white text-[10px] font-bold shadow-sm transition-all"
                  >
                    <PlusCircle className="w-3 h-3" />
                    <span>Apply Redline Fix</span>
                  </button>
                </div>
              </div>
            ))
          )}
        </div>
      )}

      {/* Tab 3: 6-Pillar Court Compliance Validator */}
      {activeTab === "compliance" && (
        <div className="flex flex-col flex-1 overflow-y-auto space-y-3 pr-1 custom-scrollbar">
          {/* Score Header */}
          <div className="p-3.5 rounded-xl bg-white border border-[#E5E4E2] flex items-center justify-between">
            <div>
              <div className="text-xs font-bold text-[#1A1A1A]">
                6-Pillar Pleading Compliance
              </div>
              <div className="text-[10px] text-[#666666]">
                {passedPillarsCount} of 6 mandatory court components detected
              </div>
            </div>
            <div className="text-right">
              <div className="text-lg font-bold font-mono text-[#1A1A1A]">
                {complianceScore}%
              </div>
              <div className="text-[9px] text-[#666666] uppercase">Audit Score</div>
            </div>
          </div>

          {/* Pillars List */}
          {compliancePillars.map((pillar) => (
            <div
              key={pillar.id}
              className={`p-3 rounded-xl border transition-all ${
                pillar.passed
                  ? "bg-[#FAFAF9] border-[#E5E4E2]"
                  : "bg-[#1A1A1A]/5 border-[#1A1A1A]/20"
              }`}
            >
              <div className="flex items-start justify-between gap-2">
                <div className="space-y-1">
                  <div className="flex items-center gap-1.5">
                    {pillar.passed ? (
                      <CheckCircle className="w-4 h-4 text-[#1A1A1A] shrink-0" />
                    ) : (
                      <AlertTriangle className="w-4 h-4 text-[#1A1A1A] shrink-0" />
                    )}
                    <h4 className="text-xs font-semibold text-[#1A1A1A]">
                      {pillar.title}
                    </h4>
                  </div>
                  <p className="text-[11px] text-[#666666]">{pillar.description}</p>
                </div>
              </div>

              {!pillar.passed && (
                <div className="mt-2.5 pt-2 border-t border-[#E5E4E2] flex items-center justify-between">
                  <span className="text-[10px] text-[#1A1A1A]">Missing from draft</span>
                  <button
                    type="button"
                    onClick={() => {
                      onInsertContent(pillar.fixText);
                      toast({
                        title: "Pillar Inserted",
                        description: `Added standard formatting for ${pillar.title}.`,
                      });
                    }}
                    className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-[#1A1A1A] hover:bg-[#2D2D2D] text-white text-[10px] font-bold transition-all"
                  >
                    <PlusCircle className="w-3 h-3" />
                    <span>Insert Component</span>
                  </button>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

