import { useState, useEffect, useRef, useMemo } from "react";
import { createPortal } from "react-dom";
import { useLocation } from "wouter";
import { ArrowLeft, Send, Loader2, MessageSquare, Gavel, Sparkles, ShieldCheck, ShieldAlert, FileText, BookOpen, ChevronDown, ChevronUp, RefreshCw, Download, BookmarkPlus, BookmarkCheck } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { LegalMarkdown } from "@/components/legal-markdown";
import { DocumentViewer } from "@/components/document-viewer";
import { Button } from "@/components/ui/button";
import { FormattedJudgmentText } from "@/components/formatted-judgment-text";
import jsPDF from "jspdf";

type AiMessage = {
  role: "user" | "assistant";
  content: string;
};

interface JudgmentData {
  citation: string;
  court: string;
  title: string;
  summary: string;
  keywords?: string[];
  uri?: string;
  source?: string;
}

interface JudgmentSummaryData {
  summary: string;
  fullText: string | null;
  source: string | null;
  verified: boolean;
}

export function setJudgmentForView(j: JudgmentData) {
  try {
    // Use localStorage (shared across tabs) so new-tab opens work.
    // sessionStorage is per-tab and breaks with window.open + noopener.
    localStorage.setItem("judgmentViewData", JSON.stringify(j));
  } catch {}
}

function getJudgmentFromStorage(): JudgmentData | null {
  try {
    const data = localStorage.getItem("judgmentViewData");
    return data ? JSON.parse(data) : null;
  } catch {
    return null;
  }
}


function stripMarkdown(text: string): string {
  return text
    .replace(/#{1,6}\s+/g, "")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/```[\s\S]*?```/g, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^[-*]\s+/gm, "- ")
    .replace(/^\d+\.\s+/gm, (m) => m)
    .trim();
}

function generateJudgmentPDF(judgment: JudgmentData, summaryData: JudgmentSummaryData | null, fullText: string | null) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 25;

  const addText = (text: string, fontSize: number, style: "normal" | "bold" | "italic" = "normal", maxWidth = contentWidth) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", style);
    const paragraphs = text.split(/\r?\n/);
    for (const paragraph of paragraphs) {
      if (paragraph.trim() === "") {
        y += fontSize * 0.45;
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        continue;
      }
      const lines = doc.splitTextToSize(paragraph, maxWidth);
      for (const line of lines) {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, margin, y);
        y += fontSize * 0.45;
      }
    }
    y += 2;
  };

  const addLine = () => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setDrawColor(180);
    doc.line(margin, y, pageWidth - margin, y);
    y += 5;
  };

  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("Al Wakeelo Digital Chambers - Judgment Report", margin, 15);
  doc.text(new Date().toLocaleDateString("en-PK", { year: "numeric", month: "long", day: "numeric" }), pageWidth - margin - 50, 15);
  doc.setTextColor(0);
  y = 25;

  addText(judgment.title, 16, "bold");
  y += 2;
  addText(`Citation: ${judgment.citation}`, 10, "bold");
  addText(`Court: ${judgment.court}`, 10, "normal");
  if (judgment.source) {
    addText(`Source: ${judgment.source === "internal" ? "Internal Registry" : "Research Feed"}`, 10, "normal");
  }
  if (judgment.keywords && judgment.keywords.length > 0) {
    addText(`Keywords: ${judgment.keywords.join(", ")}`, 9, "italic");
  }

  y += 3;
  addLine();

  // Full text first
  if (fullText) {
    addText("FULL JUDGMENT TEXT", 11, "bold");
    y += 1;
    addText(fullText, 9);
    y += 3;
    addLine();
  }

  // Then AI analysis
  if (summaryData) {
    addText("AI LEGAL ANALYSIS" + (summaryData.verified ? " (Verified Source)" : " (AI General Knowledge)"), 11, "bold");
    y += 1;
    const cleanAnalysis = stripMarkdown(summaryData.summary);
    addText(cleanAnalysis, 10);
  } else {
    addText("ORIGINAL SUMMARY", 11, "bold");
    y += 1;
    addText(judgment.summary, 10);
  }

  y += 5;
  addLine();
  doc.setFontSize(7);
  doc.setTextColor(130);
  doc.text("Generated by Al Wakeelo - AI Legal Assistant for Pakistani Law", margin, y);

  const filename = `${judgment.citation.replace(/[^a-zA-Z0-9]/g, "_")}_judgment.pdf`;
  doc.save(filename);
}

export default function JudgmentViewPage() {
  const [, setLocation] = useLocation();
  const judgment = getJudgmentFromStorage();
  const [summaryData, setSummaryData] = useState<JudgmentSummaryData | null>(null);
  const [isLoadingSummary, setIsLoadingSummary] = useState(false);
  const [summaryError, setSummaryError] = useState(false);
  // Separate state for full text (loads instantly, no AI)
  const [fullText, setFullText] = useState<string | null>(null);
  const [fullTextSource, setFullTextSource] = useState<string | null>(null);
  const [isLoadingFullText, setIsLoadingFullText] = useState(false);
  const [chatMessages, setChatMessages] = useState<AiMessage[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [isChatLoading, setIsChatLoading] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isChatMinimized, setIsChatMinimized] = useState(() => {
    try {
      return window.innerWidth < 1280;
    } catch {
      return false;
    }
  });
  const [sourceDocData, setSourceDocData] = useState<{ found: boolean; id?: number; hasSource?: boolean; sourceType?: string; sourceFilename?: string } | null>(null);
  const [sourceContent, setSourceContent] = useState<{
    found: boolean;
    title?: string;
    content?: string;
    filename?: string;
    sourceType?: string;
    mimeType?: string | null;
    originalFileAvailable?: boolean;
    viewUrl?: string | null;
  } | null>(null);
  const [isLoadingSourceContent, setIsLoadingSourceContent] = useState(false);
  const [showSourceDoc, setShowSourceDoc] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!judgment) {
      setLocation("/judgments");
      return;
    }
    // Load full text immediately (fast, no AI)
    loadFullText();
    checkIfSaved();
    checkSourceDocument();
    // Do NOT auto-trigger AI analysis
  }, []);

  async function loadFullText() {
    if (!judgment) return;
    setIsLoadingFullText(true);
    try {
      const params = new URLSearchParams({ citation: judgment.citation });
      const res = await fetch(`/api/judgment-text?${params}`, { credentials: "include" });
      if (res.ok) {
        const data = await res.json();
        setFullText(data.fullText || null);
        setFullTextSource(data.source || null);
      }
    } catch {
      // Non-fatal — full text just won't show
    }
    setIsLoadingFullText(false);
  }

  async function checkSourceDocument() {
    if (!judgment) return;
    try {
      const params = new URLSearchParams({ citation: judgment.citation });
      const res = await fetch(`/api/case-law/lookup?${params}`, { credentials: "include" });
      if (res.ok) {
        const data = await res.json();
        setSourceDocData(data);
      }
    } catch {}
  }

  async function loadSourceContent() {
    if (!sourceDocData?.id || !sourceDocData.hasSource) return;
    setIsLoadingSourceContent(true);
    try {
      const res = await fetch(`/api/case-law/${sourceDocData.id}/source`, { credentials: "include" });
      if (res.ok) {
        const data = await res.json();
        setSourceContent(data);
        if (data.found && data.viewUrl) {
          window.open(data.viewUrl, "_blank", "noopener,noreferrer");
        } else if (data.found && data.content) {
          setShowSourceDoc(true);
        }
      }
    } catch {}
    setIsLoadingSourceContent(false);
  }

  async function checkIfSaved() {
    if (!judgment) return;
    try {
      const res = await fetch("/api/saved-judgments", { credentials: "include" });
      if (res.ok) {
        const saved = await res.json();
        const exists = saved.some((j: any) => j.citation === judgment.citation && j.title === judgment.title);
        if (exists) setIsSaved(true);
      }
    } catch {}
  }

  useEffect(() => {
    if (chatEndRef.current) {
      chatEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [chatMessages]);

  async function loadSummary() {
    if (!judgment) return;
    setIsLoadingSummary(true);
    setSummaryError(false);
    try {
      const res = await apiRequest("POST", "/api/ai/judgment-summary", {
        citation: judgment.citation,
        title: judgment.title,
        court: judgment.court,
        summary: judgment.summary,
      });
      const data = await res.json();
      setSummaryData(data);
      // If the AI response also includes full text and we don't have it yet, use it
      if (data.fullText && !fullText) {
        setFullText(data.fullText);
        setFullTextSource(data.source || null);
      }
    } catch {
      setSummaryError(true);
      setSummaryData(null);
    }
    setIsLoadingSummary(false);
  }

  async function handleSaveJudgment() {
    if (!judgment || isSaving || isSaved) return;
    setIsSaving(true);
    try {
      await apiRequest("POST", "/api/saved-judgments", {
        citation: judgment.citation,
        court: judgment.court,
        title: judgment.title,
        summary: judgment.summary,
        keywords: judgment.keywords || [],
        uri: judgment.uri || null,
        source: judgment.source || null,
        aiAnalysis: summaryData?.summary || null,
      });
      setIsSaved(true);
    } catch {
      alert("Failed to save judgment. Please try again.");
    }
    setIsSaving(false);
  }

  async function handleChatSend(overrideText?: string) {
    const text = overrideText || chatInput;
    if (!text.trim() || !judgment || isChatLoading) return;
    const userMsg = text.trim();
    setChatInput("");
    setChatMessages(prev => [...prev, { role: "user", content: userMsg }]);
    setIsChatLoading(true);

    try {
      const contextText = fullText || summaryData?.fullText || summaryData?.summary || judgment.summary;
      const res = await apiRequest("POST", "/api/ai/document-chat", {
        documentType: "judgment",
        documentTitle: `${judgment.title} (${judgment.citation})`,
        documentContent: contextText,
        messages: [
          ...chatMessages.map(m => ({ role: m.role, content: m.content })),
          { role: "user", content: userMsg },
        ],
      });
      const data = await res.json();
      setChatMessages(prev => [...prev, { role: "assistant", content: data.content || "I couldn't generate a response." }]);
    } catch {
      setChatMessages(prev => [...prev, { role: "assistant", content: "Failed to get a response. Please try again." }]);
    }
    setIsChatLoading(false);
  }

  if (!judgment) return null;

  const effectiveFullText = fullText || summaryData?.fullText;

  return (
    <div className="h-full flex flex-col fade-in">
      <div className="flex items-center gap-2 md:gap-3 px-3 md:px-4 py-3 border-b border-border bg-background">
        <Button
          size="icon"
          variant="ghost"
          onClick={() => {
            if (window.history.length > 1) {
              window.history.back();
            } else {
              setLocation("/judgments");
            }
          }}
          className="text-muted-foreground flex-shrink-0"
        >
          <ArrowLeft size={18} />
        </Button>
        <div className="min-w-0 flex-1">
          <h2 className="text-sm font-bold text-foreground truncate" style={{ fontFamily: "'Playfair Display', serif" }}>
            {judgment.title}
          </h2>
          <div className="flex items-start gap-4">
            <div className="flex flex-col items-start gap-1.5">
              <p className="text-[9px] text-primary/80 uppercase tracking-wider font-bold">{judgment.citation}</p>
              {sourceDocData?.found && sourceDocData.hasSource && (
                <button
                  onClick={loadSourceContent}
                  disabled={isLoadingSourceContent}
                  className="inline-flex items-center gap-2 px-3.5 py-2 bg-emerald-600/15 text-emerald-300 text-[11px] font-extrabold uppercase tracking-[0.16em] rounded-xl border border-emerald-500/40 hover:bg-emerald-600/25 hover:text-emerald-200 transition-all disabled:opacity-50"
                  title="View linked case law document"
                >
                  {isLoadingSourceContent ? (
                    <Loader2 size={13} className="animate-spin" />
                  ) : (
                    <BookOpen size={13} />
                  )}
                  Case Doc
                </button>
              )}
            </div>
            <p className="text-[9px] text-muted-foreground uppercase tracking-wider mt-0.5">{judgment.court}</p>
          </div>
        </div>
        <div className="flex items-center gap-1.5 md:gap-2 flex-shrink-0 flex-wrap justify-end">
          <Button
            onClick={() => generateJudgmentPDF(judgment, summaryData, effectiveFullText || null)}
            className="h-9 px-4 rounded-xl bg-blue-600 hover:bg-blue-500 text-white hover:shadow-lg hover:shadow-blue-500/20 active:scale-[0.98] text-[10px] font-black uppercase tracking-wider transition-all border-none"
            title="Download as PDF"
          >
            <Download size={14} className="mr-1.5" /> PDF
          </Button>
          <Button
            variant="outline"
            onClick={handleSaveJudgment}
            disabled={isSaving || isSaved}
            className={`h-9 px-4 rounded-xl border text-[10px] font-black uppercase tracking-wider transition-all ${
              isSaved
                ? "border-emerald-500/30 text-emerald-400 hover:text-emerald-300 hover:bg-emerald-500/10"
                : "border-primary/20 text-primary hover:text-primary hover:bg-primary/10"
            }`}
            title={isSaved ? "Judgment saved" : "Save to account"}
          >
            {isSaving ? (
              <Loader2 size={14} className="animate-spin mr-1.5" />
            ) : isSaved ? (
              <BookmarkCheck size={14} className="mr-1.5" />
            ) : (
              <BookmarkPlus size={14} className="mr-1.5" />
            )}
            {isSaved ? "Saved" : "Save"}
          </Button>
          {judgment.uri && (
            <Button
              variant="outline"
              asChild
              className="h-9 px-4 rounded-xl border border-emerald-500/20 text-emerald-400 hover:text-emerald-300 hover:bg-emerald-500/10 text-[10px] font-black uppercase tracking-wider transition-all"
            >
              <a href={judgment.uri} target="_blank" rel="noopener noreferrer">
                <FileText size={14} className="mr-1.5" /> Source
              </a>
            </Button>
          )}
        </div>
      </div>

      <div className="flex-1 flex flex-col xl:flex-row overflow-visible xl:overflow-hidden">
        <div className="flex-1 overflow-y-auto">
          <div className="max-w-4xl mx-auto px-3 sm:px-6 md:px-12 py-6 md:py-10 pb-24 xl:pb-10">
            <div className="flex items-center gap-4 mb-8">
              <div className="p-3 bg-primary/10 text-primary rounded-2xl">
                <Gavel size={24} />
              </div>
              <div>
                <h1 className="text-2xl md:text-3xl font-bold text-foreground leading-snug" style={{ fontFamily: "'Playfair Display', serif" }}>
                  {judgment.title}
                </h1>
                <div className="flex flex-wrap items-center gap-3 mt-2">
                  <span className="px-3 py-1 bg-primary/10 border border-primary/20 rounded-xl text-[9px] font-black uppercase tracking-widest text-primary">
                    {judgment.citation}
                  </span>
                  <span className="px-3 py-1 bg-background border border-border rounded-xl text-[9px] font-black uppercase tracking-widest text-muted-foreground">
                    {judgment.court}
                  </span>
                  {judgment.source && (
                    <span className={`px-3 py-1 rounded-xl text-[9px] font-black uppercase tracking-widest border ${
                      judgment.source === "internal"
                        ? "bg-primary/10 border-primary/20 text-primary"
                        : "bg-blue-500/10 border-blue-500/20 text-blue-400"
                    }`}>
                      {judgment.source === "internal" ? "Internal Registry" : "Research Feed"}
                    </span>
                  )}
                </div>
              </div>
            </div>

            {judgment.keywords && judgment.keywords.length > 0 && (
              <div className="flex flex-wrap gap-2 mb-8">
                {judgment.keywords.map((kw, i) => (
                  <span key={i} className="px-3 py-1 bg-card/50 border border-border rounded-lg text-[10px] text-muted-foreground">
                    {kw}
                  </span>
                ))}
              </div>
            )}

            {/* ── FULL JUDGMENT TEXT (loads instantly, shown first) ──────── */}
            <section className="space-y-4 mb-10">
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-bold text-foreground inline-flex items-center gap-2">
                  <BookOpen size={16} className="text-primary" /> Full Judgment Text
                </h2>
                {fullTextSource && (
                  <span className="text-[9px] font-black uppercase tracking-widest text-emerald-500/60 inline-flex items-center gap-1">
                    <FileText size={10} />
                    Source: Knowledge Vault
                  </span>
                )}
              </div>

              {isLoadingFullText ? (
                <div className="rounded-2xl border border-border bg-card/40 p-6 md:p-8 flex items-center gap-3 text-muted-foreground">
                  <Loader2 size={16} className="animate-spin text-primary" />
                  <span className="text-sm">Loading judgment text...</span>
                </div>
              ) : effectiveFullText ? (
                <div className="rounded-2xl border border-border bg-card/40 p-6 md:p-8">
                  <FormattedJudgmentText text={effectiveFullText} />
                </div>
              ) : (
                <div className="rounded-2xl border border-border bg-card/40 p-6 text-muted-foreground">
                  <p className="text-sm">Full judgment text is not available in the Knowledge Vault for this citation.</p>
                  {judgment.summary && (
                    <div className="mt-4 pt-4 border-t border-border">
                      <h3 className="text-[10px] font-black uppercase tracking-widest text-muted-foreground mb-3">Head Notes</h3>
                      <p className="text-sm text-foreground leading-relaxed">{judgment.summary}</p>
                    </div>
                  )}
                </div>
              )}
            </section>

            {/* ── AI JUDGMENT ANALYSIS (on-demand, triggered by button) ── */}
            <section className="space-y-4 mb-8 border-t border-border/60 pt-8">
              {summaryData && !isLoadingSummary ? (
                <div className="space-y-6">
                  <div className="flex flex-wrap items-center gap-3">
                    <div className="w-8 h-8 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center">
                      <Sparkles size={14} className="text-primary" />
                    </div>
                    <h3 className="text-[11px] font-black uppercase tracking-widest text-primary">
                      AI Judgment Analysis
                    </h3>
                    {summaryData.verified ? (
                      <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-xl text-[9px] font-black uppercase tracking-widest bg-emerald-500/10 border border-emerald-500/20 text-emerald-400">
                        <ShieldCheck size={12} /> Verified Source
                      </span>
                    ) : (
                      <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-xl text-[9px] font-black uppercase tracking-widest bg-primary/10 border border-primary/20 text-primary">
                        <ShieldAlert size={12} /> AI General Knowledge
                      </span>
                    )}
                  </div>

                  <div className="prose prose-invert prose-sm max-w-none">
                    <LegalMarkdown content={summaryData.summary} />
                  </div>
                </div>
              ) : isLoadingSummary ? (
                <div className="flex flex-col items-center justify-center py-12 gap-4">
                  <div className="w-14 h-14 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center">
                    <Sparkles size={24} className="text-primary animate-pulse" />
                  </div>
                  <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">
                    Al Wakeelo is analyzing this judgment...
                  </p>
                </div>
              ) : summaryError ? (
                <div className="flex flex-col items-center justify-center py-8 gap-4">
                  <div className="w-14 h-14 rounded-2xl bg-red-500/10 border border-red-500/20 flex items-center justify-center">
                    <ShieldAlert size={24} className="text-red-400" />
                  </div>
                  <p className="text-sm text-muted-foreground text-center max-w-md">
                    AI analysis could not be loaded. This may be due to rate limits or a temporary issue.
                  </p>
                  <button
                    onClick={loadSummary}
                    className="inline-flex items-center gap-2 bg-primary/10 text-primary border border-primary/20 text-[10px] font-black uppercase tracking-widest py-3 px-5 rounded-xl hover:bg-primary/20 transition-all"
                  >
                    <RefreshCw size={14} /> Retry Analysis
                  </button>
                </div>
              ) : (
                /* Not yet triggered — show the Generate button */
                <div className="flex flex-col items-center justify-center py-10 gap-4">
                  <div className="w-14 h-14 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center">
                    <Sparkles size={24} className="text-primary" />
                  </div>
                  <div className="text-center">
                    <p className="text-sm font-semibold text-foreground">AI Judgment Analysis</p>
                    <p className="text-xs text-muted-foreground mt-1 max-w-sm">
                      Get a detailed AI-powered breakdown of this judgment including facts, legal issues, reasoning, and key principles.
                    </p>
                  </div>
                  <button
                    onClick={loadSummary}
                    className="inline-flex items-center gap-2.5 bg-primary text-primary-foreground text-[11px] font-black uppercase tracking-widest py-3.5 px-7 rounded-xl hover:bg-primary/90 transition-all shadow-lg shadow-primary/20"
                  >
                    <Sparkles size={14} /> Generate AI Analysis
                  </button>
                </div>
              )}
            </section>

            {showSourceDoc && sourceContent?.found && sourceContent.content && (
              <DocumentViewer
                title={sourceContent.title || judgment.citation}
                filename={sourceContent.filename}
                content={sourceContent.content}
                sourceLabel={
                  sourceDocData?.sourceType === "github" ? "Legal Library" :
                  sourceDocData?.sourceType === "admin" ? "Knowledge Vault" :
                  sourceDocData?.sourceType === "statute" ? "Statute Library" : "Source"
                }
                onClose={() => setShowSourceDoc(false)}
              />
            )}

            <div className="mt-12 pt-6 border-t border-border flex items-center justify-between flex-wrap gap-2">
              <p className="text-[8px] font-black uppercase tracking-[0.3em] text-muted-foreground">
                Al Wakeelo Digital Chambers
              </p>
            </div>
          </div>
        </div>

        {/* Mobile: Floating AI Button (minimized) — rendered via portal to escape scroll containers */}
        {isChatMinimized && window.innerWidth < 1280 && createPortal(
          <button
            className="xl:hidden fixed bottom-6 right-4 z-[9999] flex items-center gap-2 px-4 py-3 rounded-full bg-primary text-primary-foreground shadow-lg shadow-primary/30 text-xs font-bold uppercase tracking-wider hover:bg-primary/90 active:scale-95 transition-all"
            onClick={() => setIsChatMinimized(false)}
          >
            <MessageSquare size={16} />
            Ask AI
          </button>,
          document.body
        )}

        {/* Mobile: Full Chat Panel (expanded) — rendered via portal */}
        {!isChatMinimized && window.innerWidth < 1280 && createPortal(
          <div className="xl:hidden fixed bottom-0 left-0 right-0 z-[9999] h-[55vh] bg-background border-t border-border shadow-[0_-8px_30px_rgb(0,0,0,0.15)] flex flex-col rounded-t-2xl">
            {/* Header with close */}
            <div className="flex items-center justify-between px-4 py-3 border-b border-border">
              <div className="flex items-center gap-2">
                <MessageSquare size={14} className="text-primary" />
                <span className="text-[10px] font-black uppercase tracking-[0.2em] text-foreground">Ask about this judgment</span>
              </div>
              <button
                className="flex items-center gap-1 px-3 py-1.5 rounded-full border border-border bg-card text-muted-foreground text-[10px] font-bold uppercase tracking-wider hover:bg-accent hover:text-foreground active:scale-95 transition-all"
                onClick={() => setIsChatMinimized(true)}
              >
                <ChevronDown size={13} />
                Close
              </button>
            </div>

            {/* Chat Messages */}
            <div className="flex-1 overflow-y-auto p-3 space-y-3">
              {chatMessages.length === 0 && (
                <div className="text-center py-8">
                  <Gavel size={28} className="text-foreground/20 mx-auto mb-3" />
                  <p className="text-sm text-muted-foreground font-medium">Ask any question about this judgment</p>
                  <div className="mt-4 space-y-2">
                    {[
                      "What are the key legal principles?",
                      "Summarize the court's reasoning",
                      "What precedents does this set?",
                    ].map((suggestion, i) => (
                      <button
                        key={i}
                        onClick={() => handleChatSend(suggestion)}
                        disabled={isChatLoading}
                        className="w-full text-left px-4 py-3 bg-card border border-border rounded-xl text-xs text-muted-foreground hover:text-foreground hover:border-primary/30 transition-all disabled:opacity-50"
                      >
                        {suggestion}
                      </button>
                    ))}
                  </div>
                </div>
              )}
              {chatMessages.map((msg, idx) => (
                <div key={idx} className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}>
                  <div className={`max-w-[90%] px-4 py-3 rounded-xl text-sm ${msg.role === "user" ? "bg-primary text-primary-foreground" : "bg-card text-foreground border border-border"}`}>
                    {msg.role === "assistant" ? (
                      <div className="prose prose-invert prose-sm max-w-none"><LegalMarkdown content={msg.content} /></div>
                    ) : (
                      <div className="whitespace-pre-wrap text-[13px]">{msg.content}</div>
                    )}
                  </div>
                </div>
              ))}
              {isChatLoading && (
                <div className="flex justify-start">
                  <div className="bg-card border border-border rounded-xl px-4 py-3">
                    <Loader2 size={16} className="animate-spin text-primary" />
                  </div>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            {/* Input */}
            <div className="p-3 border-t border-border">
              <div className="flex gap-2">
                <input
                  className="flex-1 bg-card border border-border rounded-xl px-4 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary/50"
                  placeholder="Ask about this judgment..."
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && !e.shiftKey && handleChatSend()}
                />
                <Button size="icon" onClick={() => handleChatSend()} disabled={!chatInput.trim() || isChatLoading} className="bg-primary text-primary-foreground rounded-xl h-10 w-10">
                  <Send size={16} />
                </Button>
              </div>
            </div>
          </div>,
          document.body
        )}

        {/* Desktop: Sidebar Chat */}
        <div className="hidden xl:flex xl:flex-col xl:w-[380px] xl:min-w-[340px] xl:h-auto xl:border-l xl:border-border">
          <div className="p-3 border-b border-border flex items-center gap-2 w-full">
            <MessageSquare size={14} className="text-primary" />
            <span className="text-[10px] font-black uppercase tracking-[0.25em] text-muted-foreground">
              Ask about this judgment
            </span>
          </div>

          <div className="flex-1 overflow-y-auto p-3 md:p-4 space-y-3">
            {chatMessages.length === 0 && (
              <div className="text-center py-12">
                <Gavel size={32} className="text-foreground mx-auto mb-3" />
                <p className="text-sm text-muted-foreground font-medium">Ask any question about this judgment</p>
                <p className="text-xs text-muted-foreground mt-1">AI will analyze based on the judgment content</p>
                <div className="mt-6 space-y-2">
                  {[
                    "What are the key legal principles?",
                    "Summarize the court's reasoning",
                    "What precedents does this set?",
                  ].map((suggestion, i) => (
                    <button
                      key={i}
                      onClick={() => handleChatSend(suggestion)}
                      disabled={isChatLoading}
                      className="w-full text-left px-4 py-3 bg-card border border-border rounded-xl text-xs text-muted-foreground hover:text-foreground hover:border-primary/30 transition-all disabled:opacity-50"
                    >
                      {suggestion}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {chatMessages.map((msg, idx) => (
              <div key={idx} className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}>
                <div
                  className={`max-w-[90%] px-4 py-3 rounded-xl text-sm ${
                    msg.role === "user"
                      ? "bg-primary text-primary-foreground"
                      : "bg-card text-foreground border border-border"
                  }`}
                >
                  {msg.role === "assistant" ? (
                    <div className="prose prose-invert prose-sm max-w-none">
                      <LegalMarkdown content={msg.content} />
                    </div>
                  ) : (
                    <div className="whitespace-pre-wrap text-[13px]">{msg.content}</div>
                  )}
                </div>
              </div>
            ))}

            {isChatLoading && (
              <div className="flex justify-start">
                <div className="bg-card border border-border rounded-xl px-4 py-3">
                  <Loader2 size={16} className="animate-spin text-primary" />
                </div>
              </div>
            )}
            <div ref={chatEndRef} />
          </div>

          <div className="p-3 border-t border-border">
            <div className="flex gap-2">
              <input
                className="flex-1 bg-card border border-border rounded-xl px-4 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary/50"
                placeholder="Ask about this judgment..."
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && !e.shiftKey && handleChatSend()}
              />
              <Button
                size="icon"
                onClick={() => handleChatSend()}
                disabled={!chatInput.trim() || isChatLoading}
                className="bg-primary text-primary-foreground rounded-xl h-10 w-10"
              >
                <Send size={16} />
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
