import { useState, useEffect, useRef } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, Send, Loader2, MessageSquare, Gavel, Sparkles, ShieldCheck, ShieldAlert, FileText, BookOpen, ChevronDown, ChevronUp, RefreshCw, Download, BookmarkPlus, BookmarkCheck } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { LegalMarkdown } from "@/components/legal-markdown";
import { DocumentViewer } from "@/components/document-viewer";
import { Button } from "@/components/ui/button";
import jsPDF from "jspdf";

type AiMessage = {
  role: "user" | "assistant";
  content: string;
};

interface JudgmentData {
  citation: string;
  court: string;
  title: string;
  summary: string;
  keywords?: string[];
  uri?: string;
  source?: string;
}

interface JudgmentSummaryData {
  summary: string;
  fullText: string | null;
  source: string | null;
  verified: boolean;
}

export function setJudgmentForView(j: JudgmentData) {
  try {
    sessionStorage.setItem("judgmentViewData", JSON.stringify(j));
  } catch {}
}

function getJudgmentFromStorage(): JudgmentData | null {
  try {
    const data = sessionStorage.getItem("judgmentViewData");
    return data ? JSON.parse(data) : null;
  } catch {
    return null;
  }
}

function stripMarkdown(text: string): string {
  return text
    .replace(/#{1,6}\s+/g, "")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/```[\s\S]*?```/g, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^[-*]\s+/gm, "- ")
    .replace(/^\d+\.\s+/gm, (m) => m)
    .trim();
}

function generateJudgmentPDF(judgment: JudgmentData, summaryData: JudgmentSummaryData | null) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 25;

  const addText = (text: string, fontSize: number, style: "normal" | "bold" | "italic" = "normal", maxWidth = contentWidth) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", style);
    const lines = doc.splitTextToSize(text, maxWidth);
    for (const line of lines) {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += fontSize * 0.45;
    }
    y += 2;
  };

  const addLine = () => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setDrawColor(180);
    doc.line(margin, y, pageWidth - margin, y);
    y += 5;
  };

  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("Al Wakeelo Digital Chambers - Judgment Report", margin, 15);
  doc.text(new Date().toLocaleDateString("en-PK", { year: "numeric", month: "long", day: "numeric" }), pageWidth - margin - 50, 15);
  doc.setTextColor(0);
  y = 25;

  addText(judgment.title, 16, "bold");
  y += 2;
  addText(`Citation: ${judgment.citation}`, 10, "bold");
  addText(`Court: ${judgment.court}`, 10, "normal");
  if (judgment.source) {
    addText(`Source: ${judgment.source === "internal" ? "Internal Registry" : "Research Feed"}`, 10, "normal");
  }
  if (judgment.keywords && judgment.keywords.length > 0) {
    addText(`Keywords: ${judgment.keywords.join(", ")}`, 9, "italic");
  }

  y += 3;
  addLine();

  addText("ORIGINAL SUMMARY", 11, "bold");
  y += 1;
  addText(judgment.summary, 10);

  if (summaryData) {
    y += 3;
    addLine();
    addText("AI LEGAL ANALYSIS" + (summaryData.verified ? " (Verified Source)" : " (AI General Knowledge)"), 11, "bold");
    y += 1;
    const cleanAnalysis = stripMarkdown(summaryData.summary);
    addText(cleanAnalysis, 10);

    if (summaryData.fullText) {
      y += 3;
      addLine();
      addText("FULL JUDGMENT TEXT", 11, "bold");
      y += 1;
      addText(summaryData.fullText, 9);
    }
  }

  y += 5;
  addLine();
  doc.setFontSize(7);
  doc.setTextColor(130);
  doc.text("Generated by Al Wakeelo - AI Legal Assistant for Pakistani Law", margin, y);

  const filename = `${judgment.citation.replace(/[^a-zA-Z0-9]/g, "_")}_judgment.pdf`;
  doc.save(filename);
}

export default function JudgmentViewPage() {
  const [, setLocation] = useLocation();
  const judgment = getJudgmentFromStorage();
  const [summaryData, setSummaryData] = useState<JudgmentSummaryData | null>(null);
  const [isLoadingSummary, setIsLoadingSummary] = useState(false);
  const [summaryError, setSummaryError] = useState(false);
  const [showFullText, setShowFullText] = useState(false);
  const [chatMessages, setChatMessages] = useState<AiMessage[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [isChatLoading, setIsChatLoading] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [sourceDocData, setSourceDocData] = useState<{ found: boolean; id?: number; hasSource?: boolean; sourceType?: string; sourceFilename?: string } | null>(null);
  const [sourceContent, setSourceContent] = useState<{
    found: boolean;
    title?: string;
    content?: string;
    filename?: string;
    sourceType?: string;
    mimeType?: string | null;
    originalFileAvailable?: boolean;
    viewUrl?: string | null;
  } | null>(null);
  const [isLoadingSourceContent, setIsLoadingSourceContent] = useState(false);
  const [showSourceDoc, setShowSourceDoc] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!judgment) {
      setLocation("/judgments");
      return;
    }
    loadSummary();
    checkIfSaved();
    checkSourceDocument();
  }, []);

  async function checkSourceDocument() {
    if (!judgment) return;
    try {
      const params = new URLSearchParams({ citation: judgment.citation });
      const res = await fetch(`/api/case-law/lookup?${params}`, { credentials: "include" });
      if (res.ok) {
        const data = await res.json();
        setSourceDocData(data);
      }
    } catch {}
  }

  async function loadSourceContent() {
    if (!sourceDocData?.id || !sourceDocData.hasSource) return;
    setIsLoadingSourceContent(true);
    try {
      const res = await fetch(`/api/case-law/${sourceDocData.id}/source`, { credentials: "include" });
      if (res.ok) {
        const data = await res.json();
        setSourceContent(data);
        if (data.found && data.viewUrl) {
          window.open(data.viewUrl, "_blank", "noopener,noreferrer");
        } else if (data.found && data.content) {
          setShowSourceDoc(true);
        }
      }
    } catch {}
    setIsLoadingSourceContent(false);
  }

  async function checkIfSaved() {
    if (!judgment) return;
    try {
      const res = await fetch("/api/saved-judgments", { credentials: "include" });
      if (res.ok) {
        const saved = await res.json();
        const exists = saved.some((j: any) => j.citation === judgment.citation && j.title === judgment.title);
        if (exists) setIsSaved(true);
      }
    } catch {}
  }

  useEffect(() => {
    if (chatEndRef.current) {
      chatEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [chatMessages]);

  async function loadSummary() {
    if (!judgment) return;
    setIsLoadingSummary(true);
    setSummaryError(false);
    try {
      const res = await apiRequest("POST", "/api/ai/judgment-summary", {
        citation: judgment.citation,
        title: judgment.title,
        court: judgment.court,
        summary: judgment.summary,
      });
      const data = await res.json();
      setSummaryData(data);
    } catch {
      setSummaryError(true);
      setSummaryData(null);
    }
    setIsLoadingSummary(false);
  }

  async function handleSaveJudgment() {
    if (!judgment || isSaving || isSaved) return;
    setIsSaving(true);
    try {
      await apiRequest("POST", "/api/saved-judgments", {
        citation: judgment.citation,
        court: judgment.court,
        title: judgment.title,
        summary: judgment.summary,
        keywords: judgment.keywords || [],
        uri: judgment.uri || null,
        source: judgment.source || null,
        aiAnalysis: summaryData?.summary || null,
      });
      setIsSaved(true);
    } catch {
      alert("Failed to save judgment. Please try again.");
    }
    setIsSaving(false);
  }

  async function handleChatSend(overrideText?: string) {
    const text = overrideText || chatInput;
    if (!text.trim() || !judgment || isChatLoading) return;
    const userMsg = text.trim();
    setChatInput("");
    setChatMessages(prev => [...prev, { role: "user", content: userMsg }]);
    setIsChatLoading(true);

    try {
      const contextText = summaryData?.fullText || summaryData?.summary || judgment.summary;
      const res = await apiRequest("POST", "/api/ai/document-chat", {
        documentType: "judgment",
        documentTitle: `${judgment.title} (${judgment.citation})`,
        documentContent: contextText,
        messages: [
          ...chatMessages.map(m => ({ role: m.role, content: m.content })),
          { role: "user", content: userMsg },
        ],
      });
      const data = await res.json();
      setChatMessages(prev => [...prev, { role: "assistant", content: data.content || "I couldn't generate a response." }]);
    } catch {
      setChatMessages(prev => [...prev, { role: "assistant", content: "Failed to get a response. Please try again." }]);
    }
    setIsChatLoading(false);
  }

  if (!judgment) return null;

  return (
    <div className="h-full flex flex-col fade-in">
      <div className="flex items-center gap-2 md:gap-3 px-3 md:px-4 py-3 border-b border-slate-800 bg-[#0f172a]">
        <Button size="icon" variant="ghost" onClick={() => setLocation("/judgments")} className="text-slate-400 flex-shrink-0">
          <ArrowLeft size={18} />
        </Button>
        <div className="min-w-0 flex-1">
          <h2 className="text-sm font-bold text-white truncate" style={{ fontFamily: "'Playfair Display', serif" }}>
            {judgment.title}
          </h2>
          <div className="flex items-start gap-4">
            <div className="flex flex-col items-start gap-1.5">
              <p className="text-[9px] text-amber-500/80 uppercase tracking-wider font-bold">{judgment.citation}</p>
              {sourceDocData?.found && sourceDocData.hasSource && (
                <button
                  onClick={loadSourceContent}
                  disabled={isLoadingSourceContent}
                  className="inline-flex items-center gap-2 px-3.5 py-2 bg-emerald-600/15 text-emerald-300 text-[11px] font-extrabold uppercase tracking-[0.16em] rounded-xl border border-emerald-500/40 hover:bg-emerald-600/25 hover:text-emerald-200 transition-all disabled:opacity-50"
                  title="View linked case law document"
                >
                  {isLoadingSourceContent ? (
                    <Loader2 size={13} className="animate-spin" />
                  ) : (
                    <BookOpen size={13} />
                  )}
                  Case Doc
                </button>
              )}
            </div>
            <p className="text-[9px] text-slate-500 uppercase tracking-wider mt-0.5">{judgment.court}</p>
          </div>
        </div>
        <div className="flex items-center gap-1.5 md:gap-2 flex-shrink-0 flex-wrap justify-end">
          <button
            onClick={() => generateJudgmentPDF(judgment, summaryData)}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600/10 text-blue-400 text-[9px] font-bold uppercase tracking-widest rounded-lg hover:bg-blue-600/20 transition-all"
            title="Download as PDF"
          >
            <Download size={12} /> PDF
          </button>
          <button
            onClick={handleSaveJudgment}
            disabled={isSaving || isSaved}
            className={`flex items-center gap-1.5 px-3 py-1.5 text-[9px] font-bold uppercase tracking-widest rounded-lg transition-all ${
              isSaved
                ? "bg-amber-500/20 text-amber-400 border border-amber-500/30"
                : "bg-amber-500/10 text-amber-400 hover:bg-amber-500/20"
            }`}
            title={isSaved ? "Judgment saved" : "Save to account"}
          >
            {isSaving ? (
              <Loader2 size={12} className="animate-spin" />
            ) : isSaved ? (
              <BookmarkCheck size={12} />
            ) : (
              <BookmarkPlus size={12} />
            )}
            {isSaved ? "Saved" : "Save"}
          </button>
          {judgment.uri && (
            <a
              href={judgment.uri}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600/10 text-emerald-400 text-[9px] font-bold uppercase tracking-widest rounded-lg hover:bg-emerald-600/20 transition-all"
            >
              <FileText size={12} /> Source
            </a>
          )}
        </div>
      </div>

      <div className="flex-1 flex flex-col xl:flex-row overflow-y-auto xl:overflow-hidden">
        <div className="flex-1 overflow-y-auto">
          <div className="max-w-4xl mx-auto px-3 sm:px-6 md:px-12 py-6 md:py-10">
            <div className="flex items-center gap-4 mb-8">
              <div className="p-3 bg-amber-500/10 text-amber-500 rounded-2xl">
                <Gavel size={24} />
              </div>
              <div>
                <h1 className="text-2xl md:text-3xl font-bold text-white leading-snug" style={{ fontFamily: "'Playfair Display', serif" }}>
                  {judgment.title}
                </h1>
                <div className="flex flex-wrap items-center gap-3 mt-2">
                  <span className="px-3 py-1 bg-amber-500/10 border border-amber-500/20 rounded-xl text-[9px] font-black uppercase tracking-widest text-amber-500">
                    {judgment.citation}
                  </span>
                  <span className="px-3 py-1 bg-slate-900 border border-slate-800 rounded-xl text-[9px] font-black uppercase tracking-widest text-slate-400">
                    {judgment.court}
                  </span>
                  {judgment.source && (
                    <span className={`px-3 py-1 rounded-xl text-[9px] font-black uppercase tracking-widest border ${
                      judgment.source === "internal"
                        ? "bg-amber-500/10 border-amber-500/20 text-amber-500"
                        : "bg-blue-500/10 border-blue-500/20 text-blue-400"
                    }`}>
                      {judgment.source === "internal" ? "Internal Registry" : "Research Feed"}
                    </span>
                  )}
                </div>
              </div>
            </div>

            {judgment.keywords && judgment.keywords.length > 0 && (
              <div className="flex flex-wrap gap-2 mb-8">
                {judgment.keywords.map((kw, i) => (
                  <span key={i} className="px-3 py-1 bg-slate-800/50 border border-slate-700 rounded-lg text-[10px] text-slate-400">
                    {kw}
                  </span>
                ))}
              </div>
            )}

            <div className="mb-8 p-6 bg-[#1e293b]/50 border border-slate-800 rounded-2xl">
              <h3 className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-3">Original Summary</h3>
              <p className="text-sm text-slate-300 leading-relaxed">{judgment.summary}</p>
            </div>

            {isLoadingSummary && (
              <div className="flex flex-col items-center justify-center py-16 gap-4">
                <div className="w-14 h-14 rounded-2xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center">
                  <Sparkles size={24} className="text-amber-400 animate-pulse" />
                </div>
                <p className="text-[10px] font-black uppercase tracking-widest text-slate-600">
                  Al Wakeelo is analyzing this judgment...
                </p>
              </div>
            )}

            {summaryError && !isLoadingSummary && (
              <div className="flex flex-col items-center justify-center py-12 gap-4">
                <div className="w-14 h-14 rounded-2xl bg-red-500/10 border border-red-500/20 flex items-center justify-center">
                  <ShieldAlert size={24} className="text-red-400" />
                </div>
                <p className="text-sm text-slate-400 text-center max-w-md">
                  AI analysis could not be loaded. This may be due to rate limits or a temporary issue.
                </p>
                <button
                  onClick={loadSummary}
                  className="inline-flex items-center gap-2 bg-amber-500/10 text-amber-500 border border-amber-500/20 text-[10px] font-black uppercase tracking-widest py-3 px-5 rounded-xl hover:bg-amber-500/20 transition-all"
                >
                  <RefreshCw size={14} /> Retry Analysis
                </button>
              </div>
            )}

            {summaryData && !isLoadingSummary && (
              <div className="space-y-8">
                <div className="flex flex-wrap items-center gap-3">
                  <div className="w-8 h-8 rounded-xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center">
                    <Sparkles size={14} className="text-amber-400" />
                  </div>
                  <h3 className="text-[11px] font-black uppercase tracking-widest text-amber-400">
                    AI Judgment Analysis
                  </h3>
                  {summaryData.verified ? (
                    <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-xl text-[9px] font-black uppercase tracking-widest bg-emerald-500/10 border border-emerald-500/20 text-emerald-400">
                      <ShieldCheck size={12} /> Verified Source
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-xl text-[9px] font-black uppercase tracking-widest bg-amber-500/10 border border-amber-500/20 text-amber-400">
                      <ShieldAlert size={12} /> AI General Knowledge
                    </span>
                  )}
                </div>

                <div className="prose prose-invert prose-sm max-w-none">
                  <LegalMarkdown content={summaryData.summary} />
                </div>

                {summaryData.fullText && (
                  <div className="mt-8">
                    <button
                      onClick={() => setShowFullText(!showFullText)}
                      className="inline-flex items-center gap-2 bg-amber-500/10 text-amber-500 border border-amber-500/20 text-[10px] font-black uppercase tracking-widest py-3 px-5 rounded-xl hover:bg-amber-500/20 transition-all"
                    >
                      <BookOpen size={14} />
                      {showFullText ? "Hide Full Judgment" : "View Full Judgment"}
                      {showFullText ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                    </button>

                    {summaryData.source && (
                      <span className="ml-3 text-[9px] font-black uppercase tracking-widest text-emerald-500/60">
                        <FileText size={10} className="inline mr-1" />
                        Source: Knowledge Vault
                      </span>
                    )}

                    {showFullText && (
                      <div className="mt-6 p-6 md:p-8 bg-slate-900/50 border border-slate-800 rounded-2xl max-h-[600px] overflow-y-auto">
                        <pre className="whitespace-pre-wrap text-xs leading-relaxed text-slate-400 font-mono">
                          {summaryData.fullText}
                        </pre>
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}

            {showSourceDoc && sourceContent?.found && sourceContent.content && (
              <DocumentViewer
                title={sourceContent.title || judgment.citation}
                filename={sourceContent.filename}
                content={sourceContent.content}
                sourceLabel={
                  sourceDocData?.sourceType === "github" ? "Legal Library" :
                  sourceDocData?.sourceType === "admin" ? "Knowledge Vault" :
                  sourceDocData?.sourceType === "statute" ? "Statute Library" : "Source"
                }
                onClose={() => setShowSourceDoc(false)}
              />
            )}

            <div className="mt-12 pt-6 border-t border-slate-800 flex items-center justify-between flex-wrap gap-2">
              <p className="text-[8px] font-black uppercase tracking-[0.3em] text-slate-600">
                Al Wakeelo Digital Chambers
              </p>
            </div>
          </div>
        </div>

        <div className="w-full xl:w-[380px] xl:min-w-[340px] border-t xl:border-t-0 xl:border-l border-slate-800 bg-[#0f172a] flex flex-col max-h-[52vh] xl:max-h-none">
          <div className="p-3 md:p-4 border-b border-slate-800">
            <div className="flex items-center gap-2">
              <MessageSquare size={14} className="text-amber-500" />
              <span className="text-[10px] font-black uppercase tracking-[0.25em] text-slate-500">
                Ask about this judgment
              </span>
            </div>
          </div>

          <div className="flex-1 overflow-y-auto p-3 md:p-4 space-y-3">
            {chatMessages.length === 0 && (
              <div className="text-center py-12">
                <Gavel size={32} className="text-slate-700 mx-auto mb-3" />
                <p className="text-sm text-slate-500 font-medium">Ask any question about this judgment</p>
                <p className="text-xs text-slate-600 mt-1">AI will analyze based on the judgment content</p>
                <div className="mt-6 space-y-2">
                  {[
                    "What are the key legal principles?",
                    "Summarize the court's reasoning",
                    "What precedents does this set?",
                  ].map((suggestion, i) => (
                    <button
                      key={i}
                      onClick={() => handleChatSend(suggestion)}
                      disabled={isChatLoading}
                      className="w-full text-left px-4 py-3 bg-[#1e293b] border border-slate-800 rounded-xl text-xs text-slate-400 hover:text-white hover:border-amber-500/30 transition-all disabled:opacity-50"
                    >
                      {suggestion}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {chatMessages.map((msg, idx) => (
              <div key={idx} className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}>
                <div
                  className={`max-w-[90%] px-4 py-3 rounded-xl text-sm ${
                    msg.role === "user"
                      ? "bg-amber-500 text-slate-950"
                      : "bg-[#1e293b] text-slate-300 border border-slate-800"
                  }`}
                >
                  {msg.role === "assistant" ? (
                    <div className="prose prose-invert prose-sm max-w-none">
                      <LegalMarkdown content={msg.content} />
                    </div>
                  ) : (
                    <div className="whitespace-pre-wrap text-[13px]">{msg.content}</div>
                  )}
                </div>
              </div>
            ))}

            {isChatLoading && (
              <div className="flex justify-start">
                <div className="bg-[#1e293b] border border-slate-800 rounded-xl px-4 py-3">
                  <Loader2 size={16} className="animate-spin text-amber-500" />
                </div>
              </div>
            )}
            <div ref={chatEndRef} />
          </div>

          <div className="p-3 border-t border-slate-800">
            <div className="flex gap-2">
              <input
                className="flex-1 bg-[#1e293b] border border-slate-700 rounded-xl px-4 py-2.5 text-sm text-white placeholder:text-slate-600 focus:outline-none focus:ring-1 focus:ring-amber-500/50"
                placeholder="Ask about this judgment..."
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && !e.shiftKey && handleChatSend()}
              />
              <Button
                size="icon"
                onClick={() => handleChatSend()}
                disabled={!chatInput.trim() || isChatLoading}
                className="bg-amber-500 text-slate-950 rounded-xl h-10 w-10"
              >
                <Send size={16} />
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
